#!/bin/bash
set -euxo pipefail

# Create list of all student usernames, in case you want to loop over them later
awk -F: '$3 >= 1000 && $1 != "nobody" {print $1}' /etc/passwd > /usr/local/src/user_names.txt

# Insert your startup scripts here
