#!/bin/bash

set -eoux pipefail

cat << \EOF >/etc/motd

************************************************************************************************************
************************************************************************************************************

                     __      __  ____  _     ___  ___   _      ____     _____  ___
                     \ \    / / | |_  | |   / /  / / \ | |\/| | |_       | |  / / \
                      \_\/\/_/  |_|__ |_|__ \_\_ \_\_/ |_|  | |_|__      |_|  \_\_/

 __________    _____   __________     ___       __          ______     _______   _____   _____    __   __
|          |  / __  \ |          |   /   \     |  |        |   _  \   |   ____| /   __| /  _  \  |  \ |  |
|___|  |___| | |  | | |___|  |___|  /  ^  \    |  |        |  |_)  |  |  |__   |   /    | | | |  |   \|  |
    |  |     | |  | |     |  |     /  /_\  \   |  |        |      /   |   __|  |  |     | | | |  |       |
    |  |     | \__/ |     |  |    /  _____  \  |  |___     |  |\  \_  |  |____ |  |___  | |_| |  |  |\   |
    |__|      \_____/     |__|   /__/     \__\ |______|    |__| \___| |_______| \_____| \_____/  |__| \__|

Your name is Quaid. You have been having troubling reoccurring dreams of Mars. Your spouse tells you to
stop worrying about them but you can't shake how real they feel. In your dreams, Mars a troubling place 
where the governor is fighting a group of rebels -- while both search for a rumored alien artifact. 

One day you see an ad for a place called Rekall which offers a memory implanted vacation.  That sounds 
fun, you think.  Perhaps it could help you sleep better.  Your best friend Harry warned you this is a 
bad idea.  A really, really bad idea... but what does Harry know?  You start packing.

The next week you arrive at Rekall, but are met with a massive door blocking your way to the part of the
settlement where the Memory Vacation vendor is located.

Your first task is to find and pass through Rekall's hidden side-door, which hopefully leads to your destination.  
The IP Address of the side-door is 10.<OCTET>.0.4 although the door's port is unusual.  

Best tread carefully, though...it could be dangerous.

Helpful commands: nmap, ssh -p port_number user@ip_address
Other topics: octet

Total Recon is a hacking game designed to teach network reconnaissance with the network scanning tool 'nmap'. You
will use nmap to learn things about other hosts on the network, and progress levels using ssh. Unless otherwise noted,
all ssh connections for this scenario will use the same username and password you used to ssh to this chapter.

Remember, you can always see this message again with 'cat /etc/motd'.

*****************************************************************************************************************
*****************************************************************************************************************
EOF
