#!/bin/bash

set -eoux pipefail

cat << \EOF >/etc/motd
   ___ _ _                                  
  / __(_) | ___                             
 / _\ | | |/ _ \                            
/ /   | | |  __/                            
\/    |_|_|\___|                            
                                            
 __    __                       _           
/ / /\ \ \_ __ __ _ _ __   __ _| | ___ _ __ 
\ \/  \/ / '__/ _` | '_ \ / _` | |/ _ \ '__|
 \  /\  /| | | (_| | | | | (_| | |  __/ |   
  \/  \/ |_|  \__,_|_| |_|\__, |_|\___|_|   
                          |___/             

Welcome to the first EDURange scenario!
You can use this bash environment to try out the commands shown in the guide.
Follow the student guide and answer the questions on EDURange in browser.

The answer to the first question is:

FLAG{WELCOME}

EOF

echo 'alias sort="sort -b"' >> /etc/bash.bashrc
echo 'export TERM=xterm-256color' >> /etc/bash.bashrc
echo 'cat /etc/motd' >> /etc/bash.bashrc
